// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHslObFs9s3L2HxjRurBhORFfJhoSq0HM',
    appId: '1:817202395227:web:c00e5f0632f0e143eee77e',
    messagingSenderId: '817202395227',
    projectId: 'budget-app-a58fe',
    authDomain: 'budget-app-a58fe.firebaseapp.com',
    storageBucket: 'budget-app-a58fe.appspot.com',
    measurementId: 'G-BSCGRENB2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJq0i1bpPWCnClSakzyOw-ej_hiD1bCRc',
    appId: '1:817202395227:android:bddb2ffab01d12ddeee77e',
    messagingSenderId: '817202395227',
    projectId: 'budget-app-a58fe',
    storageBucket: 'budget-app-a58fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXPWQDtTkVcuJZh8t2uwTlQZs7fjnrgnY',
    appId: '1:817202395227:ios:4923ca6551df48b4eee77e',
    messagingSenderId: '817202395227',
    projectId: 'budget-app-a58fe',
    storageBucket: 'budget-app-a58fe.appspot.com',
    androidClientId: '817202395227-scmv88na7nm51e3peu0faccfnvi27tqg.apps.googleusercontent.com',
    iosClientId: '817202395227-79i4g21e63sh3t483jskm0q6grrvcjj7.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetAppUpdated',
  );
}
